{"name": "Проверка неуспешной авторизации курьера без одного параметра", "status": "passed", "description": "Проверяем статус 400 и текст ошибки \"Недостаточно данных для входа\"", "start": 1727511363971, "stop": 1727511364353, "uuid": "b1709053-6a47-4370-a130-9e304aa13e3e", "historyId": "1f0f8f9cef100e3a01e865081e3821f4", "testCaseId": "1f0f8f9cef100e3a01e865081e3821f4", "fullName": "tests.test_login_courier.TestLoginCourier#test_without_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-4NMD288"}, {"name": "thread", "value": "16484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}