{"name": "Проверка неуспешной повторной авторизации курьера с одинаковым логином", "status": "passed", "description": "Проверяем статус 409 и сообщением \"Этот логин уже используется. Попробуйте другой.\" в теле ответа", "start": 1727511365126, "stop": 1727511366283, "uuid": "b2e379b9-ba63-4f1a-935b-dfef0b157b02", "historyId": "98a8d11bdcad1d0376d735771f4ef5cd", "testCaseId": "98a8d11bdcad1d0376d735771f4ef5cd", "fullName": "tests.test_registration_courier.TestRegistrationCourier#test_creation_same_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_registration_courier"}, {"name": "subSuite", "value": "TestRegistrationCourier"}, {"name": "host", "value": "DESKTOP-4NMD288"}, {"name": "thread", "value": "16484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_registration_courier"}]}